version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:

  console_handler:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout

  #FOR local testing , not AWS
  file_handler:
    level: DEBUG
    formatter: standard
    class: logging.FileHandler
    filename: api.log
    mode: w

loggers:

  root:
    level: INFO
    handlers: [console_handler, file_handler]

  flask:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: no

  watchdog:
    level: ERROR
    handlers: [console_handler, file_handler]
    propagate: no

  werkzeug:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no

  # graphene_elastic:
  #   level: DEBUG
  #   handlers: [console_handler, file_handler]
  #   propagate: no

  # elasticsearch_dsl:
  #   level: DEBUG
  #   handlers: [console_handler, file_handler]
  #   propagate: no

  elasticsearch:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: no

  botocore:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no

  urllib3:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no


  backoff:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no